pipeline {
    agent any
    environment {
        PATH = "/usr/local/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh 'git clone https://github.com/carlossg/jenkinsfile-runner-lambda-example.git'
                echo 'Hello world!'
                sh 'ls -la'
            }
        }
    }
}
